
sandbox_mode = "danger-full-access"
approval_policy = "never"

model = "gpt-5-nano"
model_provider = "openai_chat"
model_reasoning_effort = "high"
model_reasoning_summary = "auto"
model_supports_reasoning_summaries = true
show_raw_agent_reasoning = true 
forced_login_method = "api"



[model_providers.openai_chat]
name = "OpenAI chat"
base_url = "http://127.0.0.1:4000/v1"
env_key = "LITELLM_KEY"
wire_api = "responses"






